permalink: pretty

collections:
  comics:
    output: true
    permalink: /comics/:path/
  art:
    output: true
    permalink: /art/:path/
  
  changelogs:
    output: false

plugins:
  - jekyll-sitemap

include:
  - draft/config.yml

