url: "https://www.sirkorgo.com"
title: "sirkorgo.com"
permalink: pretty

collections:
  comics:
    output: true
    permalink: /comics/:path/
  art:
    output: true
    permalink: /art/:path/
  changelogs:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: "/blog/rss.xml"
  excerpt_only: true
  collections:
    comics:
      path: "/comics/rss.xml"
      excerpt_only: true
    art:
      path: "/art/rss.xml"
      excerpt_only: true

include:
  - draft/config.yml
  - .well-known
