backend:
  name: github
  repo: sirkorgo/korgoweb
  branch: korgoweb5
  base_url: https://auth.sirkorgo.com
  scope: repo

media_folder: "src/post/{{slug}}"
public_folder: "/src/post/{{slug}}"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-01"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "string", default: "post" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Body", name: "body", widget: "markdown" }
