name: korgoweb4-gitlab-sync

on:
  push:
    branches:
      - korgoweb4

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: wei/git-sync@v3
        with:
          source_repo: "${{ github.repository }}"
          source_branch: "korgoweb4"
          destination_repo: "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/sirkorgo/korgoweb.git"
          destination_branch: "korgoweb4"
